model:
  _target_: birdset.modules.models.resnet.ResNetClassifier
  baseline_architecture: 'resnet18'
  num_classes: ${datamodule.dataset.n_classes}
  num_channels: 1
  pretrained: False
  pretrain_info:
    hf_path: ${datamodule.dataset.hf_path}
    hf_name: ${datamodule.dataset.hf_name}
    hf_pretrain_name: null

model_name: resnet18
model_type: vision
torch_compile: False
sampling_rate: 32_000
normalize_waveform: null
normalize_spectrogram: True